name: Package exe with PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print ec
      run: echo "$(pwd):/src/"
    - name: prince ec2
      run: echo "$PWD:/src/"
    - name: PyInstaller Windows
      run: docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows
