name: Package exe with PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      run: docker run -v "$(pwd)/src:/src/" cdrx/pyinstaller-windows

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: ./dist/windows # or path/to/artifact
