name: Package exe with PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@0.1.0a2
